name: Integration test

on: push

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        # There isn't an official TypeScript EOL policy, however security
        # updates are only shipped for the last year of releases. If people
        # don't care that they're using a version that isn't even maintained
        # for security patches, then I think they can't expect new libraries
        # are tested beyond this limit either.
        # https://github.com/microsoft/TypeScript/issues/49088#issuecomment-1169372587
        ts-version: ['4.6', '4.7', '4.8', '4.9']
    env:
      CI: true
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v3
      - name: Use Node.js lts/*
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Install TypeScript ${{ matrix.ts-version }}
        run: npm install typescript@${{ matrix.ts-version }}
      - name: Test
        run: npm run test -- integration
